"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api";
import { metric, type StatsResponse } from "@/lib/stats";
interface Key { id: string; name: string; keyPreview: string; instanceId: string; allowedModels: string[]; fallbackProviderId: string | null; lastUsed: string | null; requestCount: number; revoked: boolean; createdAt: string }
interface Instance { id: string; name: string }
export default function KeyDetailPage() {
  const id = decodeURIComponent(String(useParams().id)); const [key, setKey] = useState<Key | null>(null); const [instances, setInstances] = useState<Instance[]>([]); const [stats, setStats] = useState<StatsResponse | null>(null); const [allowlist, setAllowlist] = useState(""); const [error, setError] = useState("");
  async function load() { try { const [detail, instanceRows, performance] = await Promise.all([api.get<Key>(`/api/keys/${id}`), api.get<Instance[]>("/api/instances"), api.get<StatsResponse>(`/api/stats/key/${id}?days=30`)]); setKey(detail); setInstances(instanceRows); setStats(performance); setAllowlist(detail.allowedModels.join("\n")); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Failed to load key"); } }
  useEffect(() => { load(); }, [id]);
  async function save() { if (!key) return; const allowedModels = allowlist.split(/\n|,/).map((value) => value.trim()).filter(Boolean); if (!allowedModels.length) return setError("At least one allowlist pattern is required."); try { await api.put(`/api/keys/${id}`, { name: key.name, instanceId: key.instanceId, allowedModels, fallbackProviderId: key.fallbackProviderId || null }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Save failed"); } }
  async function revoke() { if (!confirm("Revoke this API key?")) return; await api.del(`/api/keys/${id}`); await load(); }
  if (!key) return <div>{error || "Loading API key..."}</div>;
  return <div><Link className="back-link" href="/keys">Back to API keys</Link><div className="spread page-head"><div><p className="eyebrow">API key</p><h1>{key.name}</h1><span className="mono muted">{key.keyPreview}</span></div><span className={`badge ${key.revoked ? "danger" : "success"}`}>{key.revoked ? "revoked" : "active"}</span></div>{error && <div className="notice danger">{error}</div>}<div className="detail-grid"><section className="card stack"><h2>Routing policy</h2><div className="field"><label htmlFor="key-name">Name</label><input id="key-name" value={key.name} onChange={(event) => setKey({ ...key, name: event.target.value })} /></div><div className="field"><label htmlFor="key-instance">Instance</label><select id="key-instance" value={key.instanceId} onChange={(event) => setKey({ ...key, instanceId: event.target.value })}>{instances.map((instance) => <option key={instance.id} value={instance.id}>{instance.name}</option>)}</select></div><div className="field"><label htmlFor="key-models">Allowed model patterns</label><textarea id="key-models" rows={8} value={allowlist} onChange={(event) => setAllowlist(event.target.value)} /><small className="muted">One exact ID or glob pattern per line. Use * for all models.</small></div><button className="btn-primary" disabled={key.revoked} onClick={save}>Save policy</button><button className="btn-danger" disabled={key.revoked} onClick={revoke}>Revoke key</button></section><section className="card"><h2>Status and performance</h2><dl><div><dt>Requests</dt><dd>{key.requestCount}</dd></div><div><dt>Last used</dt><dd>{key.lastUsed ? new Date(key.lastUsed).toLocaleString() : "Never"}</dd></div><div><dt>30-day samples</dt><dd>{stats?.sample.requests ?? 0} ({stats?.sample.confidence ?? "low"})</dd></div><div><dt>Latency p50</dt><dd>{metric(stats?.latency.p50 ?? null, " ms")}</dd></div><div><dt>Throughput</dt><dd>{metric(stats?.throughput.avg ?? null, " t/s")}</dd></div></dl></section></div></div>;
}
