"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect, useState } from "react";
import { api, ApiError } from "@/lib/api";
import { metric, type StatsResponse } from "@/lib/stats";

interface InstanceDetail { id: string; name: string; color: string; icon: string; modelGroupId: string | null; models: Array<{ id: string; modelId: string; providerId: string; alias: string | null; priority: number; enabled: boolean; source: string }>; groupEntries: Array<{ id: string; modelId: string; providerId: string; alias: string | null; position: number }>; keys: Array<{ id: string; name: string; keyPreview: string; requestCount: number; revoked: boolean }> }
interface Group { id: string; name: string }
export default function InstanceDetailPage() {
  const id = decodeURIComponent(String(useParams().id)); const [item, setItem] = useState<InstanceDetail | null>(null); const [groups, setGroups] = useState<Group[]>([]); const [stats, setStats] = useState<StatsResponse | null>(null); const [error, setError] = useState(""); const [modelId, setModelId] = useState(""); const [providerId, setProviderId] = useState("");
  async function load() { try { const [detail, groupRows, performance] = await Promise.all([api.get<InstanceDetail>(`/api/instances/${encodeURIComponent(id)}`), api.get<Group[]>("/api/groups"), api.get<StatsResponse>(`/api/stats/instance/${encodeURIComponent(id)}?days=30`)]); setItem(detail); setGroups(groupRows); setStats(performance); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Failed to load instance"); } }
  useEffect(() => { load(); }, [id]);
  async function save() { if (!item) return; try { await api.put(`/api/instances/${encodeURIComponent(id)}`, { name: item.name, color: item.color, modelGroupId: item.modelGroupId }); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Save failed"); } }
  async function addModel(event: React.FormEvent) { event.preventDefault(); try { await api.post(`/api/instances/${encodeURIComponent(id)}/models`, { modelId, providerId, source: "custom" }); setModelId(""); setProviderId(""); await load(); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Add failed"); } }
  async function updateModel(model: InstanceDetail["models"][number], changes: Partial<InstanceDetail["models"][number]>) { await api.put(`/api/instances/${encodeURIComponent(id)}/models/${model.id}`, changes); await load(); }
  async function removeModel(model: InstanceDetail["models"][number]) { await api.del(`/api/instances/${encodeURIComponent(id)}/models/${model.id}`); await load(); }
  if (!item) return <div>{error || "Loading instance..."}</div>;
  return <div><Link className="back-link" href="/instances">Back to instances</Link><div className="page-head"><p className="eyebrow">Routing workspace</p><h1>{item.name}</h1><span className="mono muted">{item.id}</span></div>{error && <div className="notice danger">{error}</div>}
    <div className="detail-grid"><section className="card"><h2>Settings</h2><div className="stack"><div className="field"><label htmlFor="instance-name">Name</label><input id="instance-name" value={item.name} onChange={(event) => setItem({ ...item, name: event.target.value })} /></div><div className="field"><label htmlFor="instance-color">Color</label><input id="instance-color" type="color" value={item.color} onChange={(event) => setItem({ ...item, color: event.target.value })} /></div><div className="field"><label htmlFor="instance-group">Model group</label><select id="instance-group" value={item.modelGroupId || ""} onChange={(event) => setItem({ ...item, modelGroupId: event.target.value || null })}><option value="">No group</option>{groups.map((group) => <option key={group.id} value={group.id}>{group.name}</option>)}</select></div><button className="btn-primary" onClick={save}>Save settings</button></div></section><section className="card"><h2>30-day performance</h2><dl><div><dt>Requests</dt><dd>{stats?.sample.requests ?? 0} ({stats?.sample.confidence ?? "low"})</dd></div><div><dt>Latency p50</dt><dd>{metric(stats?.latency.p50 ?? null, " ms")}</dd></div><div><dt>TTFB p50</dt><dd>{metric(stats?.ttfb.p50 ?? null, " ms")}</dd></div><div><dt>Throughput</dt><dd>{metric(stats?.throughput.avg ?? null, " t/s")}</dd></div></dl></section></div>
    <section style={{ marginTop: 24 }}><h2>Inherited group models</h2><div className="card table-scroll"><table><thead><tr><th>Model</th><th>Provider</th><th>Alias</th><th>Position</th></tr></thead><tbody>{item.groupEntries.length ? item.groupEntries.map((entry) => <tr key={entry.id}><td>{entry.modelId}</td><td>{entry.providerId}</td><td>{entry.alias || "-"}</td><td>{entry.position}</td></tr>) : <tr><td colSpan={4} className="muted">No inherited models.</td></tr>}</tbody></table></div></section>
    <section style={{ marginTop: 24 }}><h2>Direct and provider models</h2><form className="row card" onSubmit={addModel}><input value={modelId} onChange={(event) => setModelId(event.target.value)} placeholder="Canonical or raw model ID" aria-label="Canonical or raw model ID" required /><input value={providerId} onChange={(event) => setProviderId(event.target.value)} placeholder="Provider ID" aria-label="Provider ID" required /><button className="btn-primary">Add model</button></form><div className="card table-scroll"><table><thead><tr><th>Model</th><th>Provider</th><th>Alias</th><th>Priority</th><th>Enabled</th><th></th></tr></thead><tbody>{item.models.map((model) => <tr key={model.id}><td>{model.modelId}<div className="muted">{model.source}</div></td><td>{model.providerId}</td><td><input defaultValue={model.alias || ""} onBlur={(event) => updateModel(model, { alias: event.target.value })} aria-label={`Alias for ${model.modelId}`} /></td><td><input type="number" defaultValue={model.priority} onBlur={(event) => updateModel(model, { priority: Number(event.target.value) })} aria-label={`Priority for ${model.modelId}`} /></td><td><input type="checkbox" checked={model.enabled} onChange={(event) => updateModel(model, { enabled: event.target.checked })} aria-label={`Enabled for ${model.modelId}`} /></td><td><button className="btn-danger btn-sm" onClick={() => removeModel(model)}>Remove</button></td></tr>)}</tbody></table></div></section>
    <section style={{ marginTop: 24 }}><h2>Attached API keys</h2><div className="card">{item.keys.map((key) => <p key={key.id}><Link href={`/keys/${key.id}`}>{key.name}</Link> <span className="mono muted">{key.keyPreview}</span> · {key.requestCount} requests</p>)}</div></section>
  </div>;
}
