"use client";
import { useState } from "react";
import { api, ApiError } from "@/lib/api";
import { metric } from "@/lib/stats";

interface CompareResponse { kind: string; entities: Array<{ id: string; requests: number; confidence: string; successRate: number | null; avgLatency: number | null; p95Latency: number | null; avgTtfb: number | null; avgTokensPerSecond: number | null; totalCost: number | null }> }
export default function ComparePage() {
  const [kind, setKind] = useState("models"); const [ids, setIds] = useState(""); const [days, setDays] = useState(30); const [data, setData] = useState<CompareResponse | null>(null); const [error, setError] = useState("");
  async function compare() { const values = ids.split(",").map((value) => value.trim()).filter(Boolean); if (!values.length || values.length > 5) return setError("Enter one to five comma-separated IDs."); setError(""); try { setData(await api.get<CompareResponse>(`/api/stats/compare?${kind}=${encodeURIComponent(values.join(","))}&days=${days}`)); } catch (reason) { setError(reason instanceof ApiError ? reason.message : "Compare failed"); } }
  return <div><div className="page-head"><p className="eyebrow">Side-by-side evidence</p><h1>Compare</h1><p className="muted">Up to five models or providers. Low sample confidence is shown explicitly.</p></div><div className="catalog-controls card"><div className="field"><label htmlFor="compare-kind">Entity type</label><select id="compare-kind" value={kind} onChange={(event) => setKind(event.target.value)}><option value="models">Models</option><option value="providers">Providers</option></select></div><div className="field search-field"><label htmlFor="compare-ids">IDs, comma separated</label><input id="compare-ids" value={ids} onChange={(event) => setIds(event.target.value)} placeholder={kind === "models" ? "openai/gpt-5, anthropic/claude..." : "openrouter, anthropic"} /></div><div className="field"><label htmlFor="compare-range">Range</label><select id="compare-range" value={days} onChange={(event) => setDays(Number(event.target.value))}>{[1,7,30,90].map((value) => <option key={value} value={value}>{value} days</option>)}</select></div><button className="btn-primary" onClick={compare}>Compare</button></div>{error && <div className="notice danger">{error}</div>}{data && <div className="card table-scroll" style={{ marginTop: 16 }}><table><thead><tr><th>ID</th><th>Samples</th><th>Success</th><th>Latency avg / p95</th><th>TTFB</th><th>Throughput</th><th>Cost</th></tr></thead><tbody>{data.entities.map((item) => <tr key={item.id}><td className="mono">{item.id}</td><td>{item.requests} <span className="muted">({item.confidence})</span></td><td>{metric(item.successRate, "%")}</td><td>{metric(item.avgLatency, " ms")} / {metric(item.p95Latency, " ms")}</td><td>{metric(item.avgTtfb, " ms")}</td><td>{metric(item.avgTokensPerSecond, " t/s")}</td><td>{item.totalCost == null ? "Unknown" : `$${item.totalCost.toFixed(4)}`}</td></tr>)}</tbody></table></div>}</div>;
}
